### ISSUE TITLE
Create test fixture

### ISSUE THREAD

**Issue by tkindy** [tkindy/gobbler-server#4]
Because we're using mutation, we need to implement a test fixture. We have a couple strategies in mind to make it work.

**Comment by PtrTeixeira** [comment]
W/r/t test fixtures in RackUnit: [before](https://docs.racket-lang.org/rackunit/api.html#%28part._.Test_.Control_.Flow%29)

**Comment by tkindy** [comment]
Sick, thanks @PtrTeixeira!

**Comment by tkindy** [comment]
Hmm it doesn't look like `before` is the solution I'm looking for. Unless I'm missing something, it just ensures that the first expression gets evaluated before the rest of them (which seems redundant to me). I've played around with the idea, though, and this is what I've come up with:

Here's an [example](https://gist.github.com/tkindy/8370fbaef442e3c2ac453f66d31c0aaa) of the methodology I have in mind. All the _identifiers_ of the test data are defined at the top level but their actual _values_ aren't assigned until the call to `fixture`. This mutates the bogus values put into the test data identifiers (because something has to be assigned there initially) or the altered values due to running a previous test to be the proper initial data we want to run tests with.

Each test is implemented as a thunk in the `tests` list. Obviously, not every test has to be defined inline; particularly complex tests can be `define`d and dropped in by name. That list is then looped over and each test is run with (you guessed it) `run-test` which calls `fixture` before invoking the thunk to run the test.

I feel like this is a fairly clean, simple, and abstract way to handle mutation in test data. I'm open to other ideas (maybe I totally misunderstood what `before` is actually doing).

**Comment by PtrTeixeira** [comment]
Nope, you are exactly right. I misunderstood how before works; it expands the same thing as `run-test`.

**Comment by tkindy** [comment]
Implemented by #5
